### PR TITLE
Adding support for verify service

### PR DESCRIPTION
**Pull request by valenmope**
I added the ability to create and check verify service.

Hope it will be useful, I tested with my account and works well

### CODE REVIEW

**Comment by samwierema** [comment]
Hi @valenmope,

Thank you for your pull request. Our team will review the code and comment or merge as appropriate.

**Comment by valenmope** [comment]
Thanks! Hope it will be useful :-)

**Comment by samwierema** [comment]
Hi @valenmope, I'm merging this pull request and will push some changes on top of it. This is great work, thank you!

**Comment by valenmope** [comment]
Cool!

Thank you very much and congratulations for the library, it is very useful!

Best
Valentín

**Pull request merged**
