### PR TITLE
show errors also in the error message of an exception

### PR DESCRIPTION
**Pull request by michi88**
for development it is nice to have the errors also in the exception error message like:
```
ErrorException: {'code': 20, 'parameter': None, 'description': u'message not found'}
```
instead of no message at all

### CODE REVIEW

**Comment by samwierema** [comment]
Thanks for the pull request!

We're reviewing the request, and will update later today.

**Comment by samwierema** [comment]
This seems good. We'll be merging this tomorrow, and putting out a new version in PyPI.

**Comment by michi88** [comment]
Cool!

BTW: Nice api and docs, I've implemented phone number verification by text
messages within the day for https://signrequest.com.

Thanks for the effort!

Met vriendelijke groet,
Kind regards,

Michaël Krens

Mobile: +31 (0) 617 14 49 46
Business: + 31 (0) 30 711 64 81
Fax: +31 (0) 84 83 93 913

**Comment by samwierema** [comment]
Merged and released as version 1.0.3!

**Pull request merged**
